### ISSUE TITLE
Removed from organization, no longer access

### ISSUE THREAD

**Issue by sgvandijk** [ros2-gbp/ros2_v4l2_camera-release#1]
I am preparing some new releases of this package, with some new features after a bit of a hiatus, but I now found I have lost access to this repository. Could somebody give me access again, please! @nuclearsandwich helped me in the past

**Comment by nuclearsandwich** [comment]
No worries @sgvandijk. I had pruned you from the release team in order to stop spamming you with invitations. Permissions are managed via terraform scripts. I've started https://github.com/ros2-gbp/ros2-gbp-github-org/pull/114 to add you back to the release team.

**Comment by sgvandijk** [comment]
Great, thank you!
